idf_component_register(
    SRCS
        py/mpstate.c
        py/nlr.c
        py/nlrrv32.c
        py/nlrsetjmp.c
        py/malloc.c
        py/gc.c
        py/pystack.c
        py/qstr.c
        py/vstr.c
        py/mpprint.c
        py/unicode.c
        py/mpz.c
        py/reader.c
        py/lexer.c
        py/parse.c
        py/scope.c
        py/compile.c
        py/emitcommon.c
        py/emitbc.c
        py/asmbase.c
        py/asmrv32.c
        py/emitnrv32.c
        py/emitinlinerv32.c
        py/emitndebug.c
        py/formatfloat.c
        py/parsenumbase.c
        py/parsenum.c
        py/emitglue.c
        py/persistentcode.c
        py/runtime.c
        py/runtime_utils.c
        py/scheduler.c
        py/nativeglue.c
        py/pairheap.c
        py/ringbuf.c
        py/cstack.c
        py/stackctrl.c
        py/argcheck.c
        py/warning.c
        py/profile.c
        py/map.c
        py/obj.c
        py/objarray.c
        py/objattrtuple.c
        py/objbool.c
        py/objboundmeth.c
        py/objcell.c
        py/objclosure.c
        py/objcode.c
        py/objcomplex.c
        py/objdeque.c
        py/objdict.c
        py/objenumerate.c
        py/objexcept.c
        py/objfilter.c
        py/objfloat.c
        py/objfun.c
        py/objgenerator.c
        py/objgetitemiter.c
        py/objint.c
        py/objint_longlong.c
        py/objint_mpz.c
        py/objlist.c
        py/objmap.c
        py/objmodule.c
        py/objobject.c
        py/objpolyiter.c
        py/objproperty.c
        py/objnone.c
        py/objnamedtuple.c
        py/objrange.c
        py/objreversed.c
        py/objringio.c
        py/objset.c
        py/objsingleton.c
        py/objslice.c
        py/objstr.c
        py/objstrunicode.c
        py/objstringio.c
        py/objtemplate.c
        py/objtuple.c
        py/objtype.c
        py/objzip.c
        py/opmethods.c
        py/sequence.c
        py/stream.c
        py/binary.c
        py/builtinimport.c
        py/builtinevex.c
        py/builtinhelp.c
        py/modarray.c
        py/modbuiltins.c
        py/modcollections.c
        py/modgc.c
        py/modio.c
        py/modmath.c
        py/modcmath.c
        py/modmicropython.c
        py/modstring.c
        py/modstruct.c
        py/modsys.c
        py/moderrno.c
        py/modthread.c
        py/modweakref.c
        py/vm.c
        py/bc.c
        py/showbc.c
        py/repl.c
        py/smallint.c
        py/frozenmod.c
        port/embed_util.c
        port/mphalport.c
        port/tabby_interrupt.c
        shared/runtime/gchelper_generic.c
    INCLUDE_DIRS
        .
        py
        genhdr
        port
        shared
        shared/runtime
        extmod
    PRIV_REQUIRES
        esp_timer
        freertos
)

target_compile_options(${COMPONENT_LIB} PRIVATE
    -Wno-unused-parameter
    -Wno-sign-compare
    -Wno-missing-field-initializers
    -Wno-type-limits
    -Wno-unused-function
    -Wno-clobbered
    -Wno-uninitialized
    -Wno-maybe-uninitialized
    -Wno-absolute-value
)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MICROPY_NLR_SETJMP=0)
